### ISSUE TITLE
GitHub, GitLab - Year review

### ISSUE THREAD

**Issue by pylapp** [Orange-OpenSource/floss-toolbox#181]
# Description

_As a GitHub administrator,
I want to compute metrics and interesting data and facts,
So that I will be able to make a review of the year_

_As a GitLab administrator,
I want to compute metrics and interesting data and facts,
So that I will be able to make a review of the year_

# Some ideas of things to compute 

- [ ] Number of unarchived repositories
- [ ] Number of archived repositories
- [ ] Number of outside collaborators
- [ ] Number of internal collaborators
- [ ] Projects with highest number of forks
- [ ] Projects with highest number of stars
- [ ] Projects with highest number of commits
- [ ] Projects with highest number of line of code
- [ ] Projects with highest number of line of code by programming languages
- [ ] Projects with the biggest number of contributors
- [ ] Projects which has been created in the organisation
- [ ] Projects which moved from the organisation
- [ ] Top 10 programming languages in use
- [ ] Top 5 open source license in use
- [ ] People whio joined the organisation
- [ ] People who moved from the organisation

# Details

- Maybe GraphQL API could be used
- REST API should be preferred to implement quickly the feature
- Python can be nice to process data 

# TODO

- [ ] Tool for GitHub
- [ ] Tool for GitLab
- [ ] Update CHANGELOG
- [ ] Year review for 2022, 2023 and 2024 in project Discussions
- [ ] Improve scripts (with decoration, logs, etc).
